### ISSUE TITLE
Update to Electron 2.0

### ISSUE THREAD

**Issue by steipete** [PSPDFKit/pspdfkit-electron-example#1]
We need to update Electron support to Electron 2: (Released May 2nd)

https://electronjs.org/blog/electron-2-0

Backwards compatibility can be achieved via using an older checkout and is not a goal for updating support. Electron 2 should be the new required version.

Furthermore, we should also test with Electron 3 Beta:

https://electronjs.org/releases

The update to Chrome 66 (from 61) should help with WebAssembly performance.

**Comment by philipp-spiess** [comment]
PSPDFKit for Web works fine with Electron 3.0. We'll update the example soon.
