### ISSUE TITLE
Stand alone app for individual customer use

### ISSUE THREAD

**Issue by Isinlor** [PSPDFKit/pspdfkit-electron-example#2]
Hello,

I think your electron example app is **the best** PDF Viewer available on Linux. 
I have no interest in using your SDK kit to develop any app, because I think this example is already so much better than everything else out there.

My question is: Can I use it for personal purposes as an individual?

Does any of your clients sell this electron example for individual usage?

Best regards.

**Comment by steipete** [comment]
Thanks for the kind words! We don't currently have a real product here - you're of course free to "evaluate" the demo also for individual use :)

**Comment by cyptus** [comment]
i would be very interested in using this product as a standalone pdf viewer too!
is there any released product available at this time?
without an SDK license key this currently cannot be used for sure, i would be happy to pay for a "product license".

**Comment by steipete** [comment]
Thanks for the feedback and praise! We'll track and discuss this request internally.

**Comment by akosma** [comment]
I would pay for this app for Linux. As simply as that.

**Comment by akosma** [comment]
Oh, yeah, I'd still pay money for this. Oh yisssssss. Yup yup yup. No doubt about that.
